//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataManager.resource", typeof(resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\FWS\DB\BaseLayers\Baransanji.shp.
        /// </summary>
        internal static string _1_SHAPE_FILE_ {
            get {
                return ResourceManager.GetString("_1_SHAPE_FILE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\FWS\DB\BaseLayers\Subs_L3.shp.
        /// </summary>
        internal static string _2_SHPAE_FILE_ {
            get {
                return ResourceManager.GetString("_2_SHPAE_FILE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\FWS\DB\BaseLayers\Synoptic.shp.
        /// </summary>
        internal static string _3_SHAPE_FILE_ {
            get {
                return ResourceManager.GetString("_3_SHAPE_FILE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\FWS\DB\BaseLayers\ostangeo.shp.
        /// </summary>
        internal static string _5_SHAPE_FILE {
            get {
                return ResourceManager.GetString("_5_SHAPE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.
        /// </summary>
        internal static string bottomlat {
            get {
                return ResourceManager.GetString("bottomlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\IranFWS\curl\bin\curl.exe.
        /// </summary>
        internal static string curlDir {
            get {
                return ResourceManager.GetString("curlDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\FWS\DB\tmpFiles\~DBUpdate.
        /// </summary>
        internal static string DBUpdate {
            get {
                return ResourceManager.GetString("DBUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\FWS\DB\tmpFiles\DownloadLog.
        /// </summary>
        internal static string DownloadLog {
            get {
                return ResourceManager.GetString("DownloadLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\FWS\DB\tmpFiles\~DownloadQuery.
        /// </summary>
        internal static string downloadQuery {
            get {
                return ResourceManager.GetString("downloadQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\IranFWS\gdal\bin\gdal\apps\gdal_translate.exe.
        /// </summary>
        internal static string gdal_translateDir {
            get {
                return ResourceManager.GetString("gdal_translateDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\IranFWS\DataManager\gdas0p25DownloadDir.
        /// </summary>
        internal static string GDAS0p25DownloadOutputDir {
            get {
                return ResourceManager.GetString("GDAS0p25DownloadOutputDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lev_2_m_above_ground,lev_surface.
        /// </summary>
        internal static string GDAS0p25HeightList {
            get {
                return ResourceManager.GetString("GDAS0p25HeightList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\IranFWS\DataManager\gdas0p25InitDownloadDir.
        /// </summary>
        internal static string GDAS0p25InitDownloadOutputDir {
            get {
                return ResourceManager.GetString("GDAS0p25InitDownloadOutputDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lev_surface,lev_0-0.1_m_below_ground,lev_0.1-0.4_m_below_ground,lev_0.4-1_m_below_ground,lev_1-2_m_below_ground.
        /// </summary>
        internal static string gdas0p25InitHeightList {
            get {
                return ResourceManager.GetString("gdas0p25InitHeightList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var_SNOD,var_SOILW.
        /// </summary>
        internal static string gdas0p25InitVarList {
            get {
                return ResourceManager.GetString("gdas0p25InitVarList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\IranFWS\DataManager\gdas0p25TiffDir\APCP.
        /// </summary>
        internal static string GDAS0p25TiffDirAPCP {
            get {
                return ResourceManager.GetString("GDAS0p25TiffDirAPCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\IranFWS\DataManager\gdas0p25TiffDir\TEMP.
        /// </summary>
        internal static string GDAS0p25TiffDirTEMP {
            get {
                return ResourceManager.GetString("GDAS0p25TiffDirTEMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var_APCP,var_TMP.
        /// </summary>
        internal static string GDAS0p25VariablesList {
            get {
                return ResourceManager.GetString("GDAS0p25VariablesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\IranFWS\DataManager\gfs0p13DownloadDir.
        /// </summary>
        internal static string GFS0p13DownloadOutputDir {
            get {
                return ResourceManager.GetString("GFS0p13DownloadOutputDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lev_2_m_above_ground,lev_surface.
        /// </summary>
        internal static string GFS0p13HeightList {
            get {
                return ResourceManager.GetString("GFS0p13HeightList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\IranFWS\DataManager\gfs0p13InitDownloadDir.
        /// </summary>
        internal static string GFS0p13InitDownloadOutputDir {
            get {
                return ResourceManager.GetString("GFS0p13InitDownloadOutputDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lev_surface,lev_0-0.1_m_below_ground,lev_0.1-0.4_m_below_ground,lev_0.4-1_m_below_ground,lev_1-2_m_below_ground.
        /// </summary>
        internal static string gfs0p13InitHeightList {
            get {
                return ResourceManager.GetString("gfs0p13InitHeightList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var_SNOD,var_SOILW.
        /// </summary>
        internal static string gfs0p13InitVarList {
            get {
                return ResourceManager.GetString("gfs0p13InitVarList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\FWS\DB\processedData\GFS\0.13.
        /// </summary>
        internal static string GFS0p13ProcessedDB {
            get {
                return ResourceManager.GetString("GFS0p13ProcessedDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\FWS\DB\rawData\GFS\0.13.
        /// </summary>
        internal static string GFS0p13RawDataDB {
            get {
                return ResourceManager.GetString("GFS0p13RawDataDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\IranFWS\DataManager\gfs0p13TiffDir\APCP.
        /// </summary>
        internal static string GFS0p13TiffDirAPCP {
            get {
                return ResourceManager.GetString("GFS0p13TiffDirAPCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\IranFWS\DataManager\gfs0p13TiffDir\PRATE.
        /// </summary>
        internal static string GFS0p13TiffDirPRate {
            get {
                return ResourceManager.GetString("GFS0p13TiffDirPRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\IranFWS\DataManager\gfs0p13TiffDir\RAIN.
        /// </summary>
        internal static string GFS0p13TiffDirRAIN {
            get {
                return ResourceManager.GetString("GFS0p13TiffDirRAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\IranFWS\DataManager\gfs0p13TiffDir\SNOW.
        /// </summary>
        internal static string GFS0p13TiffDirSNOW {
            get {
                return ResourceManager.GetString("GFS0p13TiffDirSNOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\IranFWS\DataManager\gfs0p13TiffDir\SOILW.
        /// </summary>
        internal static string GFS0p13TiffDirSOILW {
            get {
                return ResourceManager.GetString("GFS0p13TiffDirSOILW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\IranFWS\DataManager\gfs0p13TiffDir\TEMP.
        /// </summary>
        internal static string GFS0p13TiffDirTEMP {
            get {
                return ResourceManager.GetString("GFS0p13TiffDirTEMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var_PRATE,var_TMP.
        /// </summary>
        internal static string GFS0p13VariablesList {
            get {
                return ResourceManager.GetString("GFS0p13VariablesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\IranFWS\DataManager\gfs0p25DownloadDir.
        /// </summary>
        internal static string GFS0p25DownloadOutputDir {
            get {
                return ResourceManager.GetString("GFS0p25DownloadOutputDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lev_2_m_above_ground,lev_surface.
        /// </summary>
        internal static string GFS0p25HeightList {
            get {
                return ResourceManager.GetString("GFS0p25HeightList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\IranFWS\DataManager\gfs0p25InitDownloadDir.
        /// </summary>
        internal static string GFS0p25InitDownloadOutputDir {
            get {
                return ResourceManager.GetString("GFS0p25InitDownloadOutputDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lev_surface,lev_0-0.1_m_below_ground,lev_0.1-0.4_m_below_ground,lev_0.4-1_m_below_ground,lev_1-2_m_below_ground.
        /// </summary>
        internal static string gfs0p25InitHeightList {
            get {
                return ResourceManager.GetString("gfs0p25InitHeightList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var_SNOD,var_SOILW.
        /// </summary>
        internal static string gfs0p25InitVarList {
            get {
                return ResourceManager.GetString("gfs0p25InitVarList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\FWS\DB\rawData\GFS\0.25.
        /// </summary>
        internal static string gfs0p25RawDataDB {
            get {
                return ResourceManager.GetString("gfs0p25RawDataDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\IranFWS\DataManager\gfs0p25TiffDir\APCP.
        /// </summary>
        internal static string GFS0p25TiffDirAPCP {
            get {
                return ResourceManager.GetString("GFS0p25TiffDirAPCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\IranFWS\DataManager\gfs0p25TiffDir\RAIN.
        /// </summary>
        internal static string GFS0p25TiffDirRAIN {
            get {
                return ResourceManager.GetString("GFS0p25TiffDirRAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\IranFWS\DataManager\gfs0p25TiffDir\SNOW.
        /// </summary>
        internal static string GFS0p25TiffDirSNOW {
            get {
                return ResourceManager.GetString("GFS0p25TiffDirSNOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\IranFWS\DataManager\gfs0p25TiffDir\SOILW.
        /// </summary>
        internal static string GFS0p25TiffDirSOILW {
            get {
                return ResourceManager.GetString("GFS0p25TiffDirSOILW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\IranFWS\DataManager\gfs0p25TiffDir\TEMP.
        /// </summary>
        internal static string GFS0p25TiffDirTEMP {
            get {
                return ResourceManager.GetString("GFS0p25TiffDirTEMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var_APCP,var_TMP.
        /// </summary>
        internal static string GFS0p25VariablesList {
            get {
                return ResourceManager.GetString("GFS0p25VariablesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 43.
        /// </summary>
        internal static string leftlon {
            get {
                return ResourceManager.GetString("leftlon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\FWS\DB\WebGIS\PublishGFS-RAIN.py.
        /// </summary>
        internal static string publishGFS {
            get {
                return ResourceManager.GetString("publishGFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\FWS\DB\WebGIS\PublishGFS-APCP.py.
        /// </summary>
        internal static string publishGfsApcp {
            get {
                return ResourceManager.GetString("publishGfsApcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\FWS\DB\WebGIS\PublishWRF-RAIN.py.
        /// </summary>
        internal static string publishWRF {
            get {
                return ResourceManager.GetString("publishWRF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\FWS\DB\WebGIS\PublishWRF-APCP.py.
        /// </summary>
        internal static string publishWRFAPCP {
            get {
                return ResourceManager.GetString("publishWRFAPCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64.
        /// </summary>
        internal static string rightlon {
            get {
                return ResourceManager.GetString("rightlon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\IranFWS\saga_4.0.0_win32\saga_cmd.exe.
        /// </summary>
        internal static string SagaCmdDir {
            get {
                return ResourceManager.GetString("SagaCmdDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40.
        /// </summary>
        internal static string toplat {
            get {
                return ResourceManager.GetString("toplat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\FWS\DB\WebGIS\UploadGFS-RAIN.py.
        /// </summary>
        internal static string uploadGFS {
            get {
                return ResourceManager.GetString("uploadGFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\FWS\DB\WebGIS\UploadGFS-APCP.py.
        /// </summary>
        internal static string uploadGfsApcp {
            get {
                return ResourceManager.GetString("uploadGfsApcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\FWS\DB\tmpFiles\UploadLog.
        /// </summary>
        internal static string uploadLog {
            get {
                return ResourceManager.GetString("uploadLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\FWS\DB\tmpFiles\UploadLogWRF.
        /// </summary>
        internal static string uploadLogWRF {
            get {
                return ResourceManager.GetString("uploadLogWRF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\FWS\DB\WebGIS\UploadWRF-RAIN.py.
        /// </summary>
        internal static string uploadWRF {
            get {
                return ResourceManager.GetString("uploadWRF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\FWS\DB\WebGIS\UploadWRF-APCP.py.
        /// </summary>
        internal static string uploadWRFAPCP {
            get {
                return ResourceManager.GetString("uploadWRFAPCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\FWS\DB\processedData\WRF\0.11.
        /// </summary>
        internal static string wrfProccessedDB {
            get {
                return ResourceManager.GetString("wrfProccessedDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\FWS\DB\rawData\WRF\0.11.
        /// </summary>
        internal static string wrfRawDB {
            get {
                return ResourceManager.GetString("wrfRawDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.0.0.146\Share.
        /// </summary>
        internal static string wrfTempDir {
            get {
                return ResourceManager.GetString("wrfTempDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.0.0.146\Share\APCP\ensem.
        /// </summary>
        internal static string wrfTiffDirEnsembleAPCP {
            get {
                return ResourceManager.GetString("wrfTiffDirEnsembleAPCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.0.0.146\Share\SNOW\ensem.
        /// </summary>
        internal static string wrfTiffDirEnsembleSNOW {
            get {
                return ResourceManager.GetString("wrfTiffDirEnsembleSNOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.0.0.146\Share\SOIL\ensem.
        /// </summary>
        internal static string wrfTiffDirEnsembleSOIL {
            get {
                return ResourceManager.GetString("wrfTiffDirEnsembleSOIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.0.0.146\Share\TEMP\ensem.
        /// </summary>
        internal static string wrfTiffDirEnsembleTEMP {
            get {
                return ResourceManager.GetString("wrfTiffDirEnsembleTEMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.0.0.146\Share\APCP\ferrier.
        /// </summary>
        internal static string wrfTiffDirFerrierAPCP {
            get {
                return ResourceManager.GetString("wrfTiffDirFerrierAPCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.0.0.146\Share\SNOW\ferrier.
        /// </summary>
        internal static string wrfTiffDirFerrierSNOW {
            get {
                return ResourceManager.GetString("wrfTiffDirFerrierSNOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.0.0.146\Share\SOIL\ferrier.
        /// </summary>
        internal static string wrfTiffDirFerrierSOIL {
            get {
                return ResourceManager.GetString("wrfTiffDirFerrierSOIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.0.0.146\Share\TEMP\ferrier.
        /// </summary>
        internal static string wrfTiffDirFerrierTEMP {
            get {
                return ResourceManager.GetString("wrfTiffDirFerrierTEMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.0.0.146\Share\APCP\lin.
        /// </summary>
        internal static string wrfTiffDirLinAPCP {
            get {
                return ResourceManager.GetString("wrfTiffDirLinAPCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.0.0.146\Share\SNOW\lin.
        /// </summary>
        internal static string wrfTiffDirLinSNOW {
            get {
                return ResourceManager.GetString("wrfTiffDirLinSNOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.0.0.146\Share\SOIL\lin.
        /// </summary>
        internal static string wrfTiffDirLinSOIL {
            get {
                return ResourceManager.GetString("wrfTiffDirLinSOIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.0.0.146\Share\TEMP\lin.
        /// </summary>
        internal static string wrfTiffDirLinTEMP {
            get {
                return ResourceManager.GetString("wrfTiffDirLinTEMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.0.0.146\Share\APCP\wsm6.
        /// </summary>
        internal static string wrfTiffDirWsm6APCP {
            get {
                return ResourceManager.GetString("wrfTiffDirWsm6APCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.0.0.146\Share\SNOW\wsm6.
        /// </summary>
        internal static string wrfTiffDirWsm6SNOW {
            get {
                return ResourceManager.GetString("wrfTiffDirWsm6SNOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.0.0.146\Share\SOIL\wsm6.
        /// </summary>
        internal static string wrfTiffDirWsm6SOIL {
            get {
                return ResourceManager.GetString("wrfTiffDirWsm6SOIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\10.0.0.146\Share\TEMP\wsm6.
        /// </summary>
        internal static string wrfTiffDirWsm6TEMP {
            get {
                return ResourceManager.GetString("wrfTiffDirWsm6TEMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\FWS\DB\BaseLyers\zeroRaster\ZeroGrid13.tif.
        /// </summary>
        internal static string ZeroRaster13 {
            get {
                return ResourceManager.GetString("ZeroRaster13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\FWS\DB\BaseLyers\zeroRaster\ZeroGrid25.tif.
        /// </summary>
        internal static string ZeroRaster25 {
            get {
                return ResourceManager.GetString("ZeroRaster25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\FWS\DB\BaseLyers\zeroRaster\ZeroGridWRF.tif.
        /// </summary>
        internal static string ZeroRasterWRF {
            get {
                return ResourceManager.GetString("ZeroRasterWRF", resourceCulture);
            }
        }
    }
}
